theme: jekyll-theme-minimal
title: OGraph Transformation for Software Engineers
description: On these pages we provide a number of resources for the book, including general information, expert opinions, a table of contents and downloadable authors copy, exercises, lecture slides and a discussion forum for comments and questions.
